//Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
//[TestFixture]
public class TestdonjegranicecijeneTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  //[SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  //[TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  //[Test]
  public void testdonjegranicecijene() {
    driver.Navigate().GoToUrl("https://imtec.ba/2430-imtec-preporucuje");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".from_display > .suffix")).Click();
    driver.FindElement(By.Id("p_from")).SendKeys("297");
    driver.FindElement(By.Id("p_from")).SendKeys(Keys.Enter);
    js.ExecuteScript("window.scrollTo(0,260)");
  }
}
