// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
//[TestFixture]
public class TestdodavanjaukorpuTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  //[TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  //[Test]
  public void testdodavanjaukorpu() {
    driver.Navigate().GoToUrl("https://imtec.ba/");
    driver.Manage().Window.Size = new System.Drawing.Size(596, 692);
    driver.FindElement(By.CssSelector(".ybc-menu-button-toggle_icon > .icon-bar:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".mm_menus_li_tab > .arrow")).Click();
    driver.FindElement(By.CssSelector(".open .mm_tab_name")).Click();
    driver.FindElement(By.LinkText("GAMING računari")).Click();
    driver.FindElement(By.CssSelector(".item:nth-child(1) .tvproduct-wrapper:nth-child(1) .tvproduct-defult-img")).Click();
    driver.FindElement(By.CssSelector(".add-to-cart:nth-child(1)")).Click();
    var ispis = driver.FindElement(By.Id("myModalLabel")).get
    Assert.AreEqual(ispis, "Proizvod je uspješno dodan u vašu korpu");
  }
}