// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
//[TestFixture]
public class UspjenapretragaproizvodaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
 // [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
 // [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
 // [Test]
  public void uspjenapretragaproizvoda() {
    driver.Navigate().GoToUrl("https://imtec.ba/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.Name("s")).Click();
    driver.FindElement(By.Name("s")).SendKeys("Laptop");
    driver.FindElement(By.CssSelector(".tvheader-search-btn > .material-icons")).Click();
  }
}